version: '3.3'


services:

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  db_value: