version: '3.3'


services:

#  application:
#    build:
#      context: ../application
#      dockerfile: Dockerfile
#    depends_on:
#      - db
#    env_file:
#      - ./.env

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env


volumes:
  db_value: