import os

from dotenv import load_dotenv

load_dotenv()

POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")

POSTGRES_HOST_TEST = os.getenv("POSTGRES_HOST_TEST")
POSTGRES_PORT_TEST = os.getenv("POSTGRES_PORT_TEST")
POSTGRES_DB_TEST = os.getenv("POSTGRES_DB_TEST")
POSTGRES_USER_TEST = os.getenv("POSTGRES_USER_TEST")
POSTGRES_PASSWORD_TEST = os.getenv("POSTGRES_PASSWORD_TEST")
